Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import plotly.express as px
import numpy as np

x = np.linspace(-3, 3, 101)
y0 = np.heaviside(x, 0)  # an der Stelle x=0 ist y=0
y1 = np.heaviside(x, 2)  # an der Stelle x=0 ist y=2

# Daten fÃ¼r Plotly Express vorbereiten
df = np.stack((x, y0, y1)).T
df = pd.DataFrame(df, columns=['x', 'y0', 'y1'])

# Erstellen eines Line-Plots
fig = px.line(df, x='x', y=['y0', 'y1'], title='Heaviside-Funktion')

# Layout anpassen
fig.update_layout(
    plot_bgcolor='white',
    xaxis_title='x',
    yaxis_title='y'
)

# Plot anzeigen
fig.show()

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 10[0m
[1;32m      8[0m [38;5;66;03m# Daten fÃ¼r Plotly Express vorbereiten[39;00m
[1;32m      9[0m df [38;5;241m=[39m np[38;5;241m.[39mstack((x, y0, y1))[38;5;241m.[39mT
[0;32m---> 10[0m df [38;5;241m=[39m [43mpd[49m[38;5;241m.[39mDataFrame(df, columns[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124my0[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124my1[39m[38;5;124m'[39m])
[1;32m     12[0m [38;5;66;03m# Erstellen eines Line-Plots[39;00m
[1;32m     13[0m fig [38;5;241m=[39m px[38;5;241m.[39mline(df, x[38;5;241m=[39m[38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m, y[38;5;241m=[39m[[38;5;124m'[39m[38;5;124my0[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124my1[39m[38;5;124m'[39m], title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mHeaviside-Funktion[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

